# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Independent Component Analysis (C++ Implementation)
#'
#' @param X Numeric matrix (observations x variables)
#' @param n_comp Number of independent components to extract
#' @param alg_type Algorithm type: 0 = parallel (symmetric), 1 = deflation
#' @param fun_type Nonlinearity: 0 = logcosh, 1 = exp, 2 = cube
#' @param alpha Parameter for logcosh (between 1 and 2)
#' @param whiten_method Whitening: 0 = SVD, 1 = eigendecomposition
#' @param max_iter Maximum iterations
#' @param tol Convergence tolerance
#' @param verbose Print progress
#' @param n_threads Number of OpenMP threads (0 = auto)
#' @param seed Random seed (0 = random)
#' @return List with S, A, W, K, center, iterations, converged
#'
#' @keywords internal
cpp_fastICA_dense <- function(X, n_comp, alg_type, fun_type, alpha, whiten_method, max_iter, tol, verbose, n_threads, seed) {
    .Call(`_RcppICA_cpp_fastICA_dense`, X, n_comp, alg_type, fun_type, alpha, whiten_method, max_iter, tol, verbose, n_threads, seed)
}

#' Whitening only (for testing/debugging)
#'
#' @param X Numeric matrix
#' @param n_comp Number of components
#' @param method 0 = SVD, 1 = eigen
#' @return List with X_whitened, K, K_inv, mean
#'
#' @keywords internal
cpp_whiten <- function(X, n_comp, method) {
    .Call(`_RcppICA_cpp_whiten`, X, n_comp, method)
}

